CREATE DATABASE IF NOT EXISTS CONTROL_PARQUEO;
USE CONTROL_PARQUEO;

CREATE TABLE ESPACIOS (
    IdEspacio INT AUTO_INCREMENT PRIMARY KEY,
    Numero    INT NOT NULL UNIQUE,
    Ocupado   BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE REGISTROS_PARQUEO (
    IdRegistro  INT AUTO_INCREMENT PRIMARY KEY,
    IdEspacio   INT NOT NULL,
    Placa       VARCHAR(15) NOT NULL,
    HoraEntrada DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    HoraSalida  DATETIME,
    Monto       NUMERIC(10,2),
    CONSTRAINT FK_REGPARQUEO_ESPACIOS FOREIGN KEY (IdEspacio) REFERENCES ESPACIOS (IdEspacio)
);

INSERT INTO ESPACIOS (Numero) VALUES (1), (2), (3), (4), (5);
